### ISSUE TITLE
ground truth of mulran lidar

### ISSUE THREAD

**Issue by CookieAnt** [aock/mulran2bag#1]
Hello, thank you for opening up the mulran2bag code. I would like to know how to obtain the ground truth of lidar. From the mulran dataset, there is only global_pose. csv, which seems to be the ground truth of radar, not lidar, and it is different from the lidar timestamp. I can now obtain the pose estimated by lidar slam algorithm, but I don't know how to obtain the ground truth of lidar, so I cannot estimate the error. Do you know how to obtain the pose true value of lidar？Please reply to me when you have time. Thank you!

**Comment by amock** [comment]
Hi! This project only aims to convert raw mulran files to a ros bagfile. The mulran docs say the ground truth trajectory "global_pose.csv" contains poses of the vehicles base. Did you find the other lidar-slam ground truth you mentioned somewhere in the raw files?

**Comment by CookieAnt** [comment]
> Hi! This project only aims to convert raw mulran files to a ros bagfile. The mulran docs say the ground truth trajectory "global_pose.csv" contains poses of the vehicles base. Did you find the other lidar-slam ground truth you mentioned somewhere in the raw files?
Sad, I have been searching for a long time but still haven't found the ground truth of lidar. I found that the main. m in the Mullan calibration file uses lidar timestamps to find the latest timestamp of ground_truth.csv to find lidar related pose data, which may be the ground truth of lidar. However, I found that the trajectory map of the pose found by this method deviates slightly from the ground_truth.csv trajectory map on the xy plane, so further processing may be needed. Currently, I haven't found how to proceed with the next step, or it may not be the correct method to find the ground truth.

**Comment by amock** [comment]
I cannot help you in finding the missing data since I am not the one who is providing them. I suppose, you may ask one of the authors of the paper directly.

If it turns out that you have to live with the one ground truth trajectory, I would do the following: First, you build the lidar ground truth trajectory by fetching the transform from the lidar frame to the gt frame, which is the lidar pose in the global frame. Then the trajectory could still exist of timestamps not matching the lidar stamps. But I can think of two possibilities to still do a fine comparison:
1. Search for the closest time stamp and calculate the spatial *and* time error.
2. Make your SLAM approach interpolatable between two frames so that you can find matches with zero time error. The problem here is that the final error consists not only of the SLAM error but also of the interpolation error.

**Comment by CookieAnt** [comment]
Okay, thank you for your suggestion! I will first ask the author of that paper about the true value of the trajectory, and then try if there are any other methods. Thank you very much for answering my question, and good luck!
